### ISSUE TITLE
000002 INVALID INPUT

### ISSUE THREAD

**Issue by Javierleal** [Travelport/travelport-uapi-tutorial-c-sharp#3]
Hi ..

I get the following error message appears to indicate that I have a bad at the REQ parameter , but it is correct and check it where I can see more details of this error?

**Comment by vivekjyotipramanik** [comment]
Hi Javierleal,

Thank you for your interest in Travelport Universal API. I can't see the error in your comment. Could you please give me the transaction id for the error msg or send me the req/rsp xml, I can check the details. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by Javierleal** [comment]
Muchas Gracias por la rapida Respuesta de su parte.

Les envio el REQ serielizado en JSON, aca solicitos bulos disponible para el 32 de julio desde bogota a new York, para 2 adultos y un niño.

Muchas Gracias por la rapida Respuesta de su parte.

{"AirItinerary":{"AirSegment":[{"SponsoredFltInfo":null,"CodeshareInfo":null,"AirAvailInfo":[{"BookingCodeInfo":[{"CabinClass":null,"BookingCounts":"Y7|E7|K7|H7|Q7|B7|L7|V7|R7|W7|M7|Z7|O7|U7|S7|P7"}],"FareTokenInfo":null,"ProviderCode":"1G","HostTokenRef":null}],"FlightDetails":null,"FlightDetailsRef":null,"AlternateLocationDistanceRef":null,"Connection":null,"SellMessage":null,"RailCoachDetails":null,"OpenSegmentSpecified":false,"Group":0,"Carrier":"B6","CabinClass":null,"FlightNumber":"1558","Origin":"BOG","Destination":"FLL","DepartureTime":"2015-07-31T11:29:00.000-05:00","ArrivalTime":"2015-07-31T16:19:00.000-04:00","FlightTime":"230","TravelTime":null,"Distance":"1529","ProviderCode":"1G","SupplierCode":null,"ParticipantLevel":"Secure Sell","LinkAvailability":true,"LinkAvailabilitySpecified":true,"PolledAvailabilityOption":"No polled avail exists","AvailabilityDisplayType":"Fare Shop/Optimal Shop","ClassOfService":null,"ETicketability":0,"ETicketabilitySpecified":true,"Equipment":"320","MarriageGroupSpecified":false,"NumberOfStopsSpecified":false,"SeamlessSpecified":false,"ChangeOfPlane":false,"GuaranteedPaymentCarrier":null,"HostTokenRef":null,"ProviderReservationInfoRef":null,"PassiveProviderReservationInfoRef":null,"OptionalServicesIndicator":false,"OptionalServicesIndicatorSpecified":true,"AvailabilitySource":"A","APISRequirementsRef":null,"BlackListedSpecified":false,"OperationalStatus":null,"NumberInParty":null,"RailCoachNumber":null,"SegmentRemark":null,"Key":"pLMGsJ7aS8+2YXCZQ/tqag==","Status":null,"PassiveSpecified":false,"TravelOrder":null,"ElStatSpecified":false,"KeyOverrideSpecified":false},{"SponsoredFltInfo":null,"CodeshareInfo":null,"AirAvailInfo":[{"BookingCodeInfo":[{"CabinClass":null,"BookingCounts":"Y7|E7|K7|H7|Q7|B7|L7|V7|R7|W7|M7|Z7|O7|U7|S7|P7"}],"FareTokenInfo":null,"ProviderCode":"1G","HostTokenRef":null}],"FlightDetails":null,"FlightDetailsRef":null,"AlternateLocationDistanceRef":null,"Connection":null,"SellMessage":null,"RailCoachDetails":null,"OpenSegmentSpecified":false,"Group":0,"Carrier":"B6","CabinClass":null,"FlightNumber":"302","Origin":"FLL","Destination":"JFK","DepartureTime":"2015-07-31T20:14:00.000-04:00","ArrivalTime":"2015-07-31T23:13:00.000-04:00","FlightTime":"179","TravelTime":null,"Distance":"1073","ProviderCode":"1G","SupplierCode":null,"ParticipantLevel":"Secure Sell","LinkAvailability":true,"LinkAvailabilitySpecified":true,"PolledAvailabilityOption":"No polled avail exists","AvailabilityDisplayType":"Fare Shop/Optimal Shop","ClassOfService":null,"ETicketability":0,"ETicketabilitySpecified":true,"Equipment":"320","MarriageGroupSpecified":false,"NumberOfStopsSpecified":false,"SeamlessSpecified":false,"ChangeOfPlane":false,"GuaranteedPaymentCarrier":null,"HostTokenRef":null,"ProviderReservationInfoRef":null,"PassiveProviderReservationInfoRef":null,"OptionalServicesIndicator":false,"OptionalServicesIndicatorSpecified":true,"AvailabilitySource":"A","APISRequirementsRef":null,"BlackListedSpecified":false,"OperationalStatus":null,"NumberInParty":null,"RailCoachNumber":null,"SegmentRemark":null,"Key":"Xpw+S3fYSxuPaWh21ET9Pg==","Status":null,"PassiveSpecified":false,"TravelOrder":null,"ElStatSpecified":false,"KeyOverrideSpecified":false}],"HostToken":null,"APISRequirements":null},"AirPricingModifiers":{"PermittedBookingCodes":null,"ProhibitedBookingCodes":null,"ProhibitedRuleCategories":null,"AccountCodes":null,"PermittedCabins":null,"ContractCodes":null,"ExemptTaxes":null,"PenaltyFareInformation":null,"DiscountCard":null,"PromoCodes":null,"ManualFareAdjustment":null,"PointOfSale":null,"BrandModifiers":null,"ProhibitMinStayFares":false,"ProhibitMaxStayFares":false,"CurrencyType":null,"ProhibitAdvancePurchaseFares":false,"ProhibitNonRefundableFares":false,"ProhibitRestrictedFares":false,"FaresIndicatorSpecified":false,"FiledCurrency":null,"PlatingCarrier":"B6","OverrideCarrier":null,"ETicketabilitySpecified":false,"AccountCodeFaresOnlySpecified":false,"Key":null,"ProhibitNonExchangeableFares":false,"ForceSegmentSelect":false,"InventoryRequestTypeSpecified":false,"OneWayShop":false,"ProhibitUnbundledFareTypesSpecified":false},"SearchPassenger":[{"Key":null,"Name":null,"LoyaltyCard":null,"DiscountCard":null,"PersonalGeography":null,"Code":"ADT","Age":null,"DOBSpecified":false,"Gender":null,"PricePTCOnlySpecified":false,"BookingTravelerRef":"ADT06357299438741962280","AccompaniedPassenger":false,"ResidencyTypeSpecified":false},{"Key":null,"Name":null,"LoyaltyCard":null,"DiscountCard":null,"PersonalGeography":null,"Code":"ADT","Age":null,"DOBSpecified":false,"Gender":null,"PricePTCOnlySpecified":false,"BookingTravelerRef":"ADT16357299438741962281","AccompaniedPassenger":false,"ResidencyTypeSpecified":false},{"Key":null,"Name":null,"LoyaltyCard":null,"DiscountCard":null,"PersonalGeography":null,"Code":"CNN","Age":null,"DOBSpecified":false,"Gender":null,"PricePTCOnlySpecified":false,"BookingTravelerRef":"CNN6357299438741962282","AccompaniedPassenger":false,"ResidencyTypeSpecified":false}],"AirPricingCommand":[{"AirPricingModifiers":null,"AirSegmentPricingModifiers":null,"CommandKey":null,"CabinClass":"Economy"}],"AirReservationLocatorCode":null,"OptionalServices":null,"FormOfPayment":null,"PCC":null,"CheckOBFees":false,"FareRuleType":0,"IgnoreAvailability":false,"SupplierCode":null,"TicketDateSpecified":false,"CheckFlightDetails":false,"BillingPointOfSaleInfo":{"OriginApplication":"UAPI","CIDBNumber":null},"AgentIDOverride":null,"TerminalSessionInfo":null,"TraceId":null,"TokenId":null,"AuthorizedBy":null,"TargetBranch":"P7005033","OverrideLoggingSpecified":false,"LanguageCode":null}

**Comment by Javierleal** [comment]
Excuse send the message in Spanish , Thank you for the quick response from you.

I send the REQ I serielizado in JSON , here solicitous hoaxes available for July 32 from Bogota to New York , for 2 adults and a child

{"AirItinerary":{"AirSegment":[{"SponsoredFltInfo":null,"CodeshareInfo":null,"AirAvailInfo":[{"BookingCodeInfo":[{"CabinClass":null,"BookingCounts":"Y7|E7|K7|H7|Q7|B7|L7|V7|R7|W7|M7|Z7|O7|U7|S7|P7"}],"FareTokenInfo":null,"ProviderCode":"1G","HostTokenRef":null}],"FlightDetails":null,"FlightDetailsRef":null,"AlternateLocationDistanceRef":null,"Connection":null,"SellMessage":null,"RailCoachDetails":null,"OpenSegmentSpecified":false,"Group":0,"Carrier":"B6","CabinClass":null,"FlightNumber":"1558","Origin":"BOG","Destination":"FLL","DepartureTime":"2015-07-31T11:29:00.000-05:00","ArrivalTime":"2015-07-31T16:19:00.000-04:00","FlightTime":"230","TravelTime":null,"Distance":"1529","ProviderCode":"1G","SupplierCode":null,"ParticipantLevel":"Secure Sell","LinkAvailability":true,"LinkAvailabilitySpecified":true,"PolledAvailabilityOption":"No polled avail exists","AvailabilityDisplayType":"Fare Shop/Optimal Shop","ClassOfService":null,"ETicketability":0,"ETicketabilitySpecified":true,"Equipment":"320","MarriageGroupSpecified":false,"NumberOfStopsSpecified":false,"SeamlessSpecified":false,"ChangeOfPlane":false,"GuaranteedPaymentCarrier":null,"HostTokenRef":null,"ProviderReservationInfoRef":null,"PassiveProviderReservationInfoRef":null,"OptionalServicesIndicator":false,"OptionalServicesIndicatorSpecified":true,"AvailabilitySource":"A","APISRequirementsRef":null,"BlackListedSpecified":false,"OperationalStatus":null,"NumberInParty":null,"RailCoachNumber":null,"SegmentRemark":null,"Key":"pLMGsJ7aS8+2YXCZQ/tqag==","Status":null,"PassiveSpecified":false,"TravelOrder":null,"ElStatSpecified":false,"KeyOverrideSpecified":false},{"SponsoredFltInfo":null,"CodeshareInfo":null,"AirAvailInfo":[{"BookingCodeInfo":[{"CabinClass":null,"BookingCounts":"Y7|E7|K7|H7|Q7|B7|L7|V7|R7|W7|M7|Z7|O7|U7|S7|P7"}],"FareTokenInfo":null,"ProviderCode":"1G","HostTokenRef":null}],"FlightDetails":null,"FlightDetailsRef":null,"AlternateLocationDistanceRef":null,"Connection":null,"SellMessage":null,"RailCoachDetails":null,"OpenSegmentSpecified":false,"Group":0,"Carrier":"B6","CabinClass":null,"FlightNumber":"302","Origin":"FLL","Destination":"JFK","DepartureTime":"2015-07-31T20:14:00.000-04:00","ArrivalTime":"2015-07-31T23:13:00.000-04:00","FlightTime":"179","TravelTime":null,"Distance":"1073","ProviderCode":"1G","SupplierCode":null,"ParticipantLevel":"Secure Sell","LinkAvailability":true,"LinkAvailabilitySpecified":true,"PolledAvailabilityOption":"No polled avail exists","AvailabilityDisplayType":"Fare Shop/Optimal Shop","ClassOfService":null,"ETicketability":0,"ETicketabilitySpecified":true,"Equipment":"320","MarriageGroupSpecified":false,"NumberOfStopsSpecified":false,"SeamlessSpecified":false,"ChangeOfPlane":false,"GuaranteedPaymentCarrier":null,"HostTokenRef":null,"ProviderReservationInfoRef":null,"PassiveProviderReservationInfoRef":null,"OptionalServicesIndicator":false,"OptionalServicesIndicatorSpecified":true,"AvailabilitySource":"A","APISRequirementsRef":null,"BlackListedSpecified":false,"OperationalStatus":null,"NumberInParty":null,"RailCoachNumber":null,"SegmentRemark":null,"Key":"Xpw+S3fYSxuPaWh21ET9Pg==","Status":null,"PassiveSpecified":false,"TravelOrder":null,"ElStatSpecified":false,"KeyOverrideSpecified":false}],"HostToken":null,"APISRequirements":null},"AirPricingModifiers":{"PermittedBookingCodes":null,"ProhibitedBookingCodes":null,"ProhibitedRuleCategories":null,"AccountCodes":null,"PermittedCabins":null,"ContractCodes":null,"ExemptTaxes":null,"PenaltyFareInformation":null,"DiscountCard":null,"PromoCodes":null,"ManualFareAdjustment":null,"PointOfSale":null,"BrandModifiers":null,"ProhibitMinStayFares":false,"ProhibitMaxStayFares":false,"CurrencyType":null,"ProhibitAdvancePurchaseFares":false,"ProhibitNonRefundableFares":false,"ProhibitRestrictedFares":false,"FaresIndicatorSpecified":false,"FiledCurrency":null,"PlatingCarrier":"B6","OverrideCarrier":null,"ETicketabilitySpecified":false,"AccountCodeFaresOnlySpecified":false,"Key":null,"ProhibitNonExchangeableFares":false,"ForceSegmentSelect":false,"InventoryRequestTypeSpecified":false,"OneWayShop":false,"ProhibitUnbundledFareTypesSpecified":false},"SearchPassenger":[{"Key":null,"Name":null,"LoyaltyCard":null,"DiscountCard":null,"PersonalGeography":null,"Code":"ADT","Age":null,"DOBSpecified":false,"Gender":null,"PricePTCOnlySpecified":false,"BookingTravelerRef":"ADT06357299438741962280","AccompaniedPassenger":false,"ResidencyTypeSpecified":false},{"Key":null,"Name":null,"LoyaltyCard":null,"DiscountCard":null,"PersonalGeography":null,"Code":"ADT","Age":null,"DOBSpecified":false,"Gender":null,"PricePTCOnlySpecified":false,"BookingTravelerRef":"ADT16357299438741962281","AccompaniedPassenger":false,"ResidencyTypeSpecified":false},{"Key":null,"Name":null,"LoyaltyCard":null,"DiscountCard":null,"PersonalGeography":null,"Code":"CNN","Age":null,"DOBSpecified":false,"Gender":null,"PricePTCOnlySpecified":false,"BookingTravelerRef":"CNN6357299438741962282","AccompaniedPassenger":false,"ResidencyTypeSpecified":false}],"AirPricingCommand":[{"AirPricingModifiers":null,"AirSegmentPricingModifiers":null,"CommandKey":null,"CabinClass":"Economy"}],"AirReservationLocatorCode":null,"OptionalServices":null,"FormOfPayment":null,"PCC":null,"CheckOBFees":false,"FareRuleType":0,"IgnoreAvailability":false,"SupplierCode":null,"TicketDateSpecified":false,"CheckFlightDetails":false,"BillingPointOfSaleInfo":{"OriginApplication":"UAPI","CIDBNumber":null},"AgentIDOverride":null,"TerminalSessionInfo":null,"TraceId":null,"TokenId":null,"AuthorizedBy":null,"TargetBranch":"P7005033","OverrideLoggingSpecified":false,"LanguageCode":null}

**Comment by Javierleal** [comment]
Excuse send the message in Spanish , Thank you for the quick response from you.

I send the REQ serielizado in JSON , here solicitous flights available to 32 July from Bogota to New York , for 2 adults and a child

{"AirItinerary":{"AirSegment":[{"SponsoredFltInfo":null,"CodeshareInfo":null,"AirAvailInfo":[{"BookingCodeInfo":[{"CabinClass":null,"BookingCounts":"Y7|E7|K7|H7|Q7|B7|L7|V7|R7|W7|M7|Z7|O7|U7|S7|P7"}],"FareTokenInfo":null,"ProviderCode":"1G","HostTokenRef":null}],"FlightDetails":null,"FlightDetailsRef":null,"AlternateLocationDistanceRef":null,"Connection":null,"SellMessage":null,"RailCoachDetails":null,"OpenSegmentSpecified":false,"Group":0,"Carrier":"B6","CabinClass":null,"FlightNumber":"1558","Origin":"BOG","Destination":"FLL","DepartureTime":"2015-07-31T11:29:00.000-05:00","ArrivalTime":"2015-07-31T16:19:00.000-04:00","FlightTime":"230","TravelTime":null,"Distance":"1529","ProviderCode":"1G","SupplierCode":null,"ParticipantLevel":"Secure Sell","LinkAvailability":true,"LinkAvailabilitySpecified":true,"PolledAvailabilityOption":"No polled avail exists","AvailabilityDisplayType":"Fare Shop/Optimal Shop","ClassOfService":null,"ETicketability":0,"ETicketabilitySpecified":true,"Equipment":"320","MarriageGroupSpecified":false,"NumberOfStopsSpecified":false,"SeamlessSpecified":false,"ChangeOfPlane":false,"GuaranteedPaymentCarrier":null,"HostTokenRef":null,"ProviderReservationInfoRef":null,"PassiveProviderReservationInfoRef":null,"OptionalServicesIndicator":false,"OptionalServicesIndicatorSpecified":true,"AvailabilitySource":"A","APISRequirementsRef":null,"BlackListedSpecified":false,"OperationalStatus":null,"NumberInParty":null,"RailCoachNumber":null,"SegmentRemark":null,"Key":"pLMGsJ7aS8+2YXCZQ/tqag==","Status":null,"PassiveSpecified":false,"TravelOrder":null,"ElStatSpecified":false,"KeyOverrideSpecified":false},{"SponsoredFltInfo":null,"CodeshareInfo":null,"AirAvailInfo":[{"BookingCodeInfo":[{"CabinClass":null,"BookingCounts":"Y7|E7|K7|H7|Q7|B7|L7|V7|R7|W7|M7|Z7|O7|U7|S7|P7"}],"FareTokenInfo":null,"ProviderCode":"1G","HostTokenRef":null}],"FlightDetails":null,"FlightDetailsRef":null,"AlternateLocationDistanceRef":null,"Connection":null,"SellMessage":null,"RailCoachDetails":null,"OpenSegmentSpecified":false,"Group":0,"Carrier":"B6","CabinClass":null,"FlightNumber":"302","Origin":"FLL","Destination":"JFK","DepartureTime":"2015-07-31T20:14:00.000-04:00","ArrivalTime":"2015-07-31T23:13:00.000-04:00","FlightTime":"179","TravelTime":null,"Distance":"1073","ProviderCode":"1G","SupplierCode":null,"ParticipantLevel":"Secure Sell","LinkAvailability":true,"LinkAvailabilitySpecified":true,"PolledAvailabilityOption":"No polled avail exists","AvailabilityDisplayType":"Fare Shop/Optimal Shop","ClassOfService":null,"ETicketability":0,"ETicketabilitySpecified":true,"Equipment":"320","MarriageGroupSpecified":false,"NumberOfStopsSpecified":false,"SeamlessSpecified":false,"ChangeOfPlane":false,"GuaranteedPaymentCarrier":null,"HostTokenRef":null,"ProviderReservationInfoRef":null,"PassiveProviderReservationInfoRef":null,"OptionalServicesIndicator":false,"OptionalServicesIndicatorSpecified":true,"AvailabilitySource":"A","APISRequirementsRef":null,"BlackListedSpecified":false,"OperationalStatus":null,"NumberInParty":null,"RailCoachNumber":null,"SegmentRemark":null,"Key":"Xpw+S3fYSxuPaWh21ET9Pg==","Status":null,"PassiveSpecified":false,"TravelOrder":null,"ElStatSpecified":false,"KeyOverrideSpecified":false}],"HostToken":null,"APISRequirements":null},"AirPricingModifiers":{"PermittedBookingCodes":null,"ProhibitedBookingCodes":null,"ProhibitedRuleCategories":null,"AccountCodes":null,"PermittedCabins":null,"ContractCodes":null,"ExemptTaxes":null,"PenaltyFareInformation":null,"DiscountCard":null,"PromoCodes":null,"ManualFareAdjustment":null,"PointOfSale":null,"BrandModifiers":null,"ProhibitMinStayFares":false,"ProhibitMaxStayFares":false,"CurrencyType":null,"ProhibitAdvancePurchaseFares":false,"ProhibitNonRefundableFares":false,"ProhibitRestrictedFares":false,"FaresIndicatorSpecified":false,"FiledCurrency":null,"PlatingCarrier":"B6","OverrideCarrier":null,"ETicketabilitySpecified":false,"AccountCodeFaresOnlySpecified":false,"Key":null,"ProhibitNonExchangeableFares":false,"ForceSegmentSelect":false,"InventoryRequestTypeSpecified":false,"OneWayShop":false,"ProhibitUnbundledFareTypesSpecified":false},"SearchPassenger":[{"Key":null,"Name":null,"LoyaltyCard":null,"DiscountCard":null,"PersonalGeography":null,"Code":"ADT","Age":null,"DOBSpecified":false,"Gender":null,"PricePTCOnlySpecified":false,"BookingTravelerRef":"ADT06357299438741962280","AccompaniedPassenger":false,"ResidencyTypeSpecified":false},{"Key":null,"Name":null,"LoyaltyCard":null,"DiscountCard":null,"PersonalGeography":null,"Code":"ADT","Age":null,"DOBSpecified":false,"Gender":null,"PricePTCOnlySpecified":false,"BookingTravelerRef":"ADT16357299438741962281","AccompaniedPassenger":false,"ResidencyTypeSpecified":false},{"Key":null,"Name":null,"LoyaltyCard":null,"DiscountCard":null,"PersonalGeography":null,"Code":"CNN","Age":null,"DOBSpecified":false,"Gender":null,"PricePTCOnlySpecified":false,"BookingTravelerRef":"CNN6357299438741962282","AccompaniedPassenger":false,"ResidencyTypeSpecified":false}],"AirPricingCommand":[{"AirPricingModifiers":null,"AirSegmentPricingModifiers":null,"CommandKey":null,"CabinClass":"Economy"}],"AirReservationLocatorCode":null,"OptionalServices":null,"FormOfPayment":null,"PCC":null,"CheckOBFees":false,"FareRuleType":0,"IgnoreAvailability":false,"SupplierCode":null,"TicketDateSpecified":false,"CheckFlightDetails":false,"BillingPointOfSaleInfo":{"OriginApplication":"UAPI","CIDBNumber":null},"AgentIDOverride":null,"TerminalSessionInfo":null,"TraceId":null,"TokenId":null,"AuthorizedBy":null,"TargetBranch":"P7005033","OverrideLoggingSpecified":false,"LanguageCode":null}

**Comment by vivekjyotipramanik** [comment]
Hi Javierleal,

I am seeing in the request you are sending lots of null value. Please don't use any null values and that is the reason the req is failing. Please remove the attributes which has null values from the req and the request should run fine. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by Javierleal** [comment]
Sorry but there are many nulls, in the example you give equally there are many nulls no way to know which is the parameter specifically because I am siguiedo the same example the difference is not working ..

**Comment by Javierleal** [comment]
Sorry but there are many nulls, in the example you give equally there are many nulls no way to know which is the parameter specifically because I am siguiedo the same example the difference is not working ..

**Comment by vivekjyotipramanik** [comment]
Hi Javierleal,

Please refer to the below link to build the XML, the sample created based on minimum data required to get LowFareSearchResponse. Please find below the link with all the samples. Please let me know how it goes. Thanks.

https://support.travelport.com/webhelp/uapi/Content/SampleWeb/Samples_Air-Galileo.htm#024

https://support.travelport.com/webhelp/uapi/uAPI.htm#SampleWeb/Samples_Overview.htm%3FTocPath%3DSamples%7C_____0


Thanks & Regards
Vivekjyoti Pramanik

**Comment by vivekjyotipramanik** [comment]
Hi Javierleal,

There is another point I wanted to make, uAPI is based on Soap webservices. I would recommend you to use XML instead of JSON. Could you please confirm which programming language are you using, is it Java/C# or something else. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by Javierleal** [comment]
Hi, I 'm working with C # but the JSON to send him has nothing to do with the functions apply, send so that 's what I had on hand ... I am using the project that you get here on GitHub and use it without changing any code and made ​​the same mistake .. will be something with my credentials ?

**Comment by Javierleal** [comment]
Sorry insistence , in this demo you GitHub colcan in the C # is the same mistake it ran almost completely change any code .. and nothing will change the AirPriceReq

**Comment by vivekjyotipramanik** [comment]
Hi Javierleal,

Apologies, I don't understand, is the code from Github not working? What are the issues you are getting.
Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by Javierleal** [comment]
Yes, the code GitHub that you published download it again, run and gives the error Invalid Input 000002 , happens to invoke the AirPricePort

**Comment by vivekjyotipramanik** [comment]
Hi Javierleal,

I just ran a test with the code we uploaded yesterday in github and we are unable to recreate the issue. Please send me the transaction id from the response or the complete response. The transaction id can be retrieved from the AirPriceRsp object structure. Could you please let me know which cities you are trying with. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by Javierleal** [comment]
Try my temporary credentials and a few days left to expire , so no matter the post .
    <add key = " Username" value = " Universal API / uAPI5722156754 - a27dccbe " />
    <add key = " Password" value = " x5WpdJtKcFw67X383TPMaRpcP " />
    <add key = " 1GTargetBranch " value = " P7005033 " />

**Comment by Javierleal** [comment]
Username" value = " Universal API / uAPI5722156754 - a27dccbe " 
Password" value = " x5WpdJtKcFw67X383TPMaRpcP " 
1GTargetBranch " value = " P7005033 "

**Comment by vivekjyotipramanik** [comment]
Hi Javierleal,

Looks like it is an issue with your credential. Could you please try again once you get the new credential. Thanks. 

Thanks & Regards
Vivekjyoti Pramanik

**Comment by Javierleal** [comment]
Ok , I'm intentanto request a new credential , but there is an error in the portal usteds know why?

https://developer.travelport.com/app/developer-network/request-formpage

**Comment by vivekjyotipramanik** [comment]
Hi Javierleal,

There is an ongoing issue in the credential request page. We are trying to fix this as soon as possible. I will notify you once the site is up. In the meantime we will try to fix you existing credential. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by Javierleal** [comment]
Ok , thank you ,  i will wait then

**Comment by EdmundMorris** [comment]
@vivekjyotipramanik @Javierleal Did the fixed credentials work? I have been following the Java tutorial and get exactly the same error message: "000002 INVALID INPUT" when submitting a AirPriceReq. Searching worked fine, it's just the Price request which failed. The response also contains the message "3101: Invalid input data. Generic data validation failure message" but I am unsure what part of the request is invalid.

**Comment by EdmundMorris** [comment]
Just in case anyone else is getting this issue, it's a problem with the credentials. You cannot make AirPriceReq requests with the sandbox credentials, you need a full account.

**Comment by vivekjyotipramanik** [comment]
Hi EdmundMorris,

Thank you for your interest in Travelport Universal API. You can do AirPriceReq with trial credentials.
Could you please share your TragetBranch and Username and we can check the issues with the credentials. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
Thanks @vivekjyotipramanik. Here are my credentials:

Universal API User ID:  Universal API/uAPI3703332121-2cc8dfb0
Universal API Password:  ps4hBQ3p9Qre7kjbTK3cKBZ2r
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7004952

**Comment by EdmundMorris** [comment]
@vivekjyotipramanik sorry to ask so soon, but have you had any progress with this? We're eager to get this issue resolved as the 30 trial period is running out

**Comment by EdmundMorris** [comment]
Hi @vivekjyotipramanik. Hope you had a good weekend. Has there been any progress with checking out the credentials?

**Comment by vivekjyotipramanik** [comment]
Hi EdmundMorris,

Apologies for the delayed response. We are working on this and as soon as it is resolved I will provide an update. In the meantime, Please feel free to request for another set of trial credentials. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
Thanks Vivekjyoti. Anything you can do would be greatly appreciated, we're under quite a bit of pressure from our client at the moment. 

Thanks,
Ed

**Comment by vivekjyotipramanik** [comment]
Hi EdmundMorris,

Could you please try with this again. If it does not work, Please open a test access request and you will be provided an available trial credentials. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
Hi Vivekjyoti. I'm afraid it's still not working. Rather than using my own application, I logged into the demo.travelportuniversalapi.com site but same thing happened: I was able to search but the AirPriceReq request failed. I'll request new trial credentials and see if this works. Thanks

**Comment by EdmundMorris** [comment]
I've created a new account but I get the same error. @vivekjyotipramanik Are you sure this is possible to send a AirPriceReq using trial credentials?

**Comment by vivekjyotipramanik** [comment]
Hi Ed,

We are sure that using trial credentials AirPrice works and it worked for us with your credentials as well.
Could you please provide me the Request you are using. It looks like it is a problem with the Airport and the dates. Please provide the req and response and we will analyze this. Please let me know how it goes. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
LowFareSearchReq: https://gist.github.com/EdmundMorris/5c91bd4cb5a644e1c03aec14a1e93719
LowFareSearchRsp: https://gist.github.com/EdmundMorris/acd9a4380f2e67ad643677907e7a547f
AirPriceReq: https://gist.github.com/EdmundMorris/3030a422ca9c7a244224c8cdf2e06d9c
AirPriceRsp: https://gist.github.com/EdmundMorris/825e990326731232546e6417dc4945c8

**Comment by vivekjyotipramanik** [comment]
Hi Ed,

Could you please remove the below part from the AirPriceReq and try again. Please let me know how it goes. Thanks.

```xml
<AirPricingModifiers InventoryRequestType="DirectAccess">
    <BrandModifiers ModifierType="FareFamilyDisplay" />
  </AirPricingModifiers>
```

Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
Hi @vivekjyotipramanik. I'm fairly convinced that AirPriceReq requests cannot be made with the sandbox credentials. I have tried logging in to the test site (demo.travelportuniversalapi.com) with two sets of trial credentials which both failed after the initial search with the 000002 INVALID INPUT error. I can get the site to work by logging out from my trial account and using the default production or pre-production credentials. This suggests that it is nothing to do with my application / code because the XML requests are entirely created and processed by the example website. I'm really eager to get this resolved as soon as possible. Any idea what we could try to get the trial credentials working with the test website? Thanks in advance - Ed.

**Comment by vivekjyotipramanik** [comment]
Hi Ed,

The demosite also use the tag ModifierType="FareFamilyDisplay" while doing AirPriceReq and there is a problem going on with ModifierType="FareFamilyDisplay". Please do not use demosite to test this. Please run a AirPriceReq without ModifierType="FareFamilyDisplay". Please do not use the below tag and the AirPriceReq should work fine. There are a number of developers in github using trial credentials and are successfully running AirpirceReq. It is a problem  with the below tag and not the AirPreiceReq or your credentials. Please remove the below tag and run the AirPriceReq and Please let me know how it goes. Thanks.

```xml
<AirPricingModifiers InventoryRequestType="DirectAccess">
    <BrandModifiers ModifierType="FareFamilyDisplay" />
  </AirPricingModifiers>
```
Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
Hi Vivekjyoti. No luck, I'm afraid. https://gist.github.com/EdmundMorris/53b61b72e8aa2a956642480f0b4fcfad

Does everything else look ok with the request? Thanks

**Comment by vivekjyotipramanik** [comment]
Hi Ed,

Please change the OriginApplication to UAPI. Please let me know how it goes. Thanks.

<ns2:BillingPointOfSaleInfo OriginApplication="UAPI"/>

Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
Still nothing. Is there any way of taking the guess work out of equation? Eg are there server logs that can be looked up using the transaction ID or trace ID? Thanks, Ed

https://gist.github.com/EdmundMorris/411b9af2507c30f734097a202f7171aa

**Comment by vivekjyotipramanik** [comment]
Hi Ed,

We are analyzing the logs and will provide an update as soon as possible. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
Great, thank you

**Comment by vivekjyotipramanik** [comment]
Hi Ed,

We have analyzed the logs and it looks like there is some internal setting which is causing the issue you are facing with your credential. We are working on this internally to fix this issue and will provide an update soon. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
Thanks for the update Vivekjyoti.

**Comment by EdmundMorris** [comment]
Hi @vivekjyotipramanik. The 30 day period has expired so I'm using the second set of trial credentials I created. Here are the details:

````
Universal API User ID:  Universal API/uAPI6828794020-e9d96a12
Branch Code (TargetBranch) for ProviderName (ProviderCode):  Branch Code for Galileo (1G): P7005024
````

Any luck with the fix? Thanks, Ed

**Comment by EdmundMorris** [comment]
Hi Vivekjyoti. Do you have an ETA on the fix? Most of our code for API is written, just waiting on the fix to test it. Sorry to rush you! Thanks, Ed.

**Comment by vivekjyotipramanik** [comment]
Hi Ed,

Apologies, We have checked and looks like it is not a provisioning issue and our internal team is working on this issue. We can not provide any estimated timeline for this as internal teams are still investigating on this one. I am working and trying to provide a set of credentials which will work for you. 

Apologies for the delay. Thank you for your patience. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
Thanks. I appreciate all that you're doing to get this resolved Vivekjyoti.

**Comment by EdmundMorris** [comment]
Hi Vivekjyoti. We have a big milestone on Wednesday, so hoping to get this resolved by then. Any luck with the credentials? Thanks

**Comment by vivekjyotipramanik** [comment]
Hi Ed,

We are trying our best to resolve this situation. It is working for all the other trial credentials, somehow for the trial credentials you have and another set of trial credential from another user are having the issue.
I will provide an update by tomorrow about this. Thank you for your patience. Thanks.

Thanks & Regards
Vivekjyoti Pramanik

**Comment by EdmundMorris** [comment]
Hi Vivekjyoti. I've received an email saying that my second trial credentials are expiring. Any luck getting new working test credentials? Thanks

**Comment by vivekjyotipramanik** [comment]
Hi Ed,

I have already asked the internal team to provide a working set of credentials. I will provide an update as soon as I receive them. Thanks.

Thanks & Regards
Vivekjyoti Pramanik
